"""Serialization utilities using joblib and JSON."""

import json
from pathlib import Path
from typing import Any, Union

import joblib

from mlpipe.core.exceptions import ArtifactError


def save_joblib(obj: Any, path: Union[str, Path]) -> Path:
    """Save a Python object using joblib."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        joblib.dump(obj, path)
        return path
    except Exception as e:
        raise ArtifactError(
            f"Failed to serialize object to '{path}': {e}",
            "Check disk permissions and available space."
        )


def load_joblib(path: Union[str, Path]) -> Any:
    """Load a Python object from a joblib file."""
    path = Path(path)
    if not path.exists():
        raise ArtifactError(
            f"Joblib file not found at '{path}'.",
            "Verify that the file path is correct."
        )
    try:
        return joblib.load(path)
    except Exception as e:
        raise ArtifactError(
            f"Failed to load object from '{path}': {e}",
            "Ensure the file was generated by a compatible version of joblib and scikit-learn."
        )


def save_json(data: Any, path: Union[str, Path], indent: int = 2) -> Path:
    """Save data structure to formatted JSON."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=indent, default=str)
        return path
    except Exception as e:
        raise ArtifactError(
            f"Failed to write JSON artifact to '{path}': {e}",
            "Verify write permissions."
        )


def load_json(path: Union[str, Path]) -> Any:
    """Load data from a JSON file."""
    path = Path(path)
    if not path.exists():
        raise ArtifactError(f"JSON artifact not found at '{path}'.")
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        raise ArtifactError(f"Failed to parse JSON artifact from '{path}': {e}")
