"""
Standalone Python code generator for MLPipe.

Generates self-contained, reproducible Python scripts using only standard pandas,
numpy, scikit-learn, and joblib with zero dependence on MLPipe.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
import pprint


MODEL_IMPORTS = {
    "Logistic Regression": ("sklearn.linear_model", "LogisticRegression"),
    "Random Forest": {
        "classification": ("sklearn.ensemble", "RandomForestClassifier"),
        "regression": ("sklearn.ensemble", "RandomForestRegressor"),
    },
    "HistGradientBoosting": {
        "classification": ("sklearn.ensemble", "HistGradientBoostingClassifier"),
        "regression": ("sklearn.ensemble", "HistGradientBoostingRegressor"),
    },
    "Decision Tree": {
        "classification": ("sklearn.tree", "DecisionTreeClassifier"),
        "regression": ("sklearn.tree", "DecisionTreeRegressor"),
    },
    "K-Nearest Neighbors": {
        "classification": ("sklearn.neighbors", "KNeighborsClassifier"),
        "regression": ("sklearn.neighbors", "KNeighborsRegressor"),
    },
    "Ridge Regression": ("sklearn.linear_model", "Ridge"),
    "Linear Regression": ("sklearn.linear_model", "LinearRegression"),
}


def _get_model_import_and_class(model_name: str, task_type: str) -> tuple[str, str]:
    """Resolve module path and class name for a given model."""
    for key, spec in MODEL_IMPORTS.items():
        if key.lower() in model_name.lower():
            if isinstance(spec, dict):
                return spec[task_type]
            return spec

    # Default fallback
    if task_type == "classification":
        return ("sklearn.ensemble", "RandomForestClassifier")
    return ("sklearn.ensemble", "RandomForestRegressor")


def generate_standalone_code(
    dataset_path: str,
    target_column: str,
    task_type: str,
    model_name: str,
    estimator_params: Dict[str, Any],
    numeric_columns: List[str],
    categorical_columns: List[str],
    test_size: float = 0.20,
    random_seed: int = 42,
) -> str:
    """
    Generate clean, idiomatic Python code reproducing the fitted ML pipeline.

    Args:
        dataset_path: Path or filename of the CSV data.
        target_column: Name of the target column.
        task_type: 'classification' or 'regression'.
        model_name: Name of the model.
        estimator_params: Best hyperparameters dictionary.
        numeric_columns: List of numeric features.
        categorical_columns: List of categorical features.
        test_size: Train/test split ratio.
        random_seed: Seed for reproducibility.

    Returns:
        Complete standalone Python script as a string.
    """
    mod_path, class_name = _get_model_import_and_class(model_name, task_type)

    # Filter estimator parameters to relevant, serializable kwargs
    clean_params = {}
    for k, v in estimator_params.items():
        if k.startswith("_") or callable(v):
            continue
        if isinstance(v, (int, float, str, bool, list)) or v is None:
            clean_params[k] = v

    formatted_params = pprint.pformat(clean_params, indent=4, width=80)

    # Evaluation imports and code depending on task
    if task_type == "classification":
        metrics_import = "from sklearn.metrics import accuracy_score, classification_report, f1_score, roc_auc_score"
        stratify_arg = "stratify=y,"
        eval_code = """    # Generate predictions
    y_pred = pipeline.predict(X_test)
    
    print("\\n=== Model Evaluation (Test Set) ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(f"F1 Score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
    print("\\nClassification Report:")
    print(classification_report(y_test, y_pred))

    if hasattr(pipeline, "predict_proba"):
        try:
            y_proba = pipeline.predict_proba(X_test)
            if y_proba.shape[1] == 2:
                print(f"ROC-AUC Score: {roc_auc_score(y_test, y_proba[:, 1]):.4f}")
        except Exception:
            pass"""
    else:
        metrics_import = "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score"
        stratify_arg = ""
        eval_code = """    # Generate predictions
    y_pred = pipeline.predict(X_test)
    
    print("\\n=== Model Evaluation (Test Set) ===")
    print(f"R² Score:  {r2_score(y_test, y_pred):.4f}")
    print(f"MAE:       {mean_absolute_error(y_test, y_pred):.4f}")
    print(f"RMSE:      {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")"""

    # Escape path
    norm_path = dataset_path.replace("\\", "/")

    code = f'''"""
Standalone Machine Learning Pipeline
Generated by MLPipe (https://github.com/atharva081106/mlpipe)

This script is self-contained and reproducible.
Dependencies required:
    pip install pandas numpy scikit-learn joblib
"""

from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
{metrics_import}
from {mod_path} import {class_name}
import joblib


def main():
    # ── 1. Load Dataset ──────────────────────────────────────────────────────────
    data_path = "{norm_path}"
    print(f"Loading dataset from: {{data_path}}")
    df = pd.read_csv(data_path)
    target_column = "{target_column}"

    # Drop rows where target is missing
    df = df.dropna(subset=[target_column]).reset_index(drop=True)

    X = df.drop(columns=[target_column])
    y = df[target_column]
    print(f"Dataset shape: {{X.shape[0]}} rows, {{X.shape[1]}} features")

    # ── 2. Train / Test Split ────────────────────────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size={test_size},
        random_state={random_seed},
        {stratify_arg}
    )
    print(f"Training set: {{len(X_train)}} samples | Testing set: {{len(X_test)}} samples")

    # ── 3. Preprocessing Setup ───────────────────────────────────────────────────
    numeric_features = {numeric_columns}
    categorical_features = {categorical_columns}

    # Intersect with actual features present
    numeric_cols = [c for c in numeric_features if c in X.columns]
    categorical_cols = [c for c in categorical_features if c in X.columns]

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ])

    transformers = []
    if numeric_cols:
        transformers.append(("num", numeric_transformer, numeric_cols))
    if categorical_cols:
        transformers.append(("cat", categorical_transformer, categorical_cols))

    if not transformers:
        # Automatic column inference fallback
        num_auto = X.select_dtypes(include=[np.number]).columns.tolist()
        cat_auto = [c for c in X.columns if c not in num_auto]
        if num_auto:
            transformers.append(("num", numeric_transformer, num_auto))
        if cat_auto:
            transformers.append(("cat", categorical_transformer, cat_auto))

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop",
    )

    # ── 4. Model Initialization & Pipeline Construction ──────────────────────────
    model_params = {formatted_params}
    estimator = {class_name}(**model_params)

    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("estimator", estimator),
    ])

    # ── 5. Model Training ────────────────────────────────────────────────────────
    print("\\nTraining pipeline with {model_name}...")
    pipeline.fit(X_train, y_train)
    print("Training complete!")

    # ── 6. Evaluation ────────────────────────────────────────────────────────────
{eval_code}

    # ── 7. Save Trained Artifact ─────────────────────────────────────────────────
    output_model_path = "pipeline.joblib"
    joblib.dump(pipeline, output_model_path)
    print(f"\\nPipeline successfully saved to: {{output_model_path}}")

    # ── 8. Example Prediction Usage ──────────────────────────────────────────────
    sample_test = X_test.head(3)
    sample_preds = pipeline.predict(sample_test)
    print("\\nSample Predictions on first 3 test rows:")
    for i, pred in enumerate(sample_preds):
        print(f"  Row {{i+1}}: Predicted={{pred}}")


if __name__ == "__main__":
    main()
'''
    return code
